"""initial

Revision ID: 140c6a9f4071
Revises: 
Create Date: 2024-08-05 17:07:28.333763

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "140c6a9f4071"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=16), nullable=False),
        sa.Column("description", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_genders_id"), "genders", ["id"], unique=False)
    op.create_index(op.f("ix_genders_name"), "genders", ["name"], unique=True)
    op.create_table(
        "places",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("address", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_places_address"), "places", ["address"], unique=False
    )
    op.create_index(op.f("ix_places_id"), "places", ["id"], unique=False)
    op.create_index(op.f("ix_places_name"), "places", ["name"], unique=False)
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profiles_id"), "profiles", ["id"], unique=False)
    op.create_index(
        op.f("ix_profiles_name"), "profiles", ["name"], unique=True
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=12), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=50), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_services_id"), "services", ["id"], unique=False)
    op.create_index(
        op.f("ix_services_name"), "services", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_services_profile_id"),
        "services",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=12), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hashed_password"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_login"), "users", ["login"], unique=True)
    op.create_index(
        op.f("ix_users_role_id"), "users", ["role_id"], unique=False
    )
    op.create_table(
        "doctors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("surname", sa.String(length=30), nullable=False),
        sa.Column("patronymic", sa.String(length=30), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("gender_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gender_id"],
            ["genders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_doctors_gender_id"), "doctors", ["gender_id"], unique=False
    )
    op.create_index(op.f("ix_doctors_id"), "doctors", ["id"], unique=False)
    op.create_index(op.f("ix_doctors_name"), "doctors", ["name"], unique=False)
    op.create_index(
        op.f("ix_doctors_profile_id"), "doctors", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_doctors_user_id"), "doctors", ["user_id"], unique=False
    )
    op.create_table(
        "patients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("surname", sa.String(length=30), nullable=False),
        sa.Column("patronymic", sa.String(length=30), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("address", sa.String(length=256), nullable=False),
        sa.Column("gender_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gender_id"],
            ["genders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_patients_address"), "patients", ["address"], unique=False
    )
    op.create_index(
        op.f("ix_patients_birth_date"),
        "patients",
        ["birth_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patients_gender_id"), "patients", ["gender_id"], unique=False
    )
    op.create_index(op.f("ix_patients_id"), "patients", ["id"], unique=False)
    op.create_index(
        op.f("ix_patients_user_id"), "patients", ["user_id"], unique=False
    )
    op.create_table(
        "appointments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("place_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_appointments_date"), "appointments", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_appointments_doctor_id"),
        "appointments",
        ["doctor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointments_id"), "appointments", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_appointments_patient_id"),
        "appointments",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointments_place_id"),
        "appointments",
        ["place_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointments_service_id"),
        "appointments",
        ["service_id"],
        unique=False,
    )
    op.create_table(
        "experiences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("position", sa.String(length=20), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiences_doctor_id"),
        "experiences",
        ["doctor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiences_id"), "experiences", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_experiences_name"), "experiences", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_experiences_start_date"),
        "experiences",
        ["start_date"],
        unique=False,
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("rate", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("place_id", sa.Integer(), nullable=False),
        sa.CheckConstraint("rate BETWEEN 0 AND 5", name="rate_check"),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reviews_doctor_id"), "reviews", ["doctor_id"], unique=False
    )
    op.create_index(op.f("ix_reviews_id"), "reviews", ["id"], unique=False)
    op.create_index(
        op.f("ix_reviews_place_id"), "reviews", ["place_id"], unique=False
    )
    op.create_index(op.f("ix_reviews_rate"), "reviews", ["rate"], unique=False)
    op.create_table(
        "visits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("symptom", sa.String(length=128), nullable=False),
        sa.Column("diagnosis", sa.String(length=64), nullable=False),
        sa.Column("instruction", sa.String(length=256), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("place_id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_visits_appointment_id"),
        "visits",
        ["appointment_id"],
        unique=False,
    )
    op.create_index(op.f("ix_visits_date"), "visits", ["date"], unique=False)
    op.create_index(
        op.f("ix_visits_doctor_id"), "visits", ["doctor_id"], unique=False
    )
    op.create_index(op.f("ix_visits_id"), "visits", ["id"], unique=False)
    op.create_index(
        op.f("ix_visits_patient_id"), "visits", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_visits_place_id"), "visits", ["place_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_visits_place_id"), table_name="visits")
    op.drop_index(op.f("ix_visits_patient_id"), table_name="visits")
    op.drop_index(op.f("ix_visits_id"), table_name="visits")
    op.drop_index(op.f("ix_visits_doctor_id"), table_name="visits")
    op.drop_index(op.f("ix_visits_date"), table_name="visits")
    op.drop_index(op.f("ix_visits_appointment_id"), table_name="visits")
    op.drop_table("visits")
    op.drop_index(op.f("ix_reviews_rate"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_place_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_doctor_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_experiences_start_date"), table_name="experiences")
    op.drop_index(op.f("ix_experiences_name"), table_name="experiences")
    op.drop_index(op.f("ix_experiences_id"), table_name="experiences")
    op.drop_index(op.f("ix_experiences_doctor_id"), table_name="experiences")
    op.drop_table("experiences")
    op.drop_index(
        op.f("ix_appointments_service_id"), table_name="appointments"
    )
    op.drop_index(op.f("ix_appointments_place_id"), table_name="appointments")
    op.drop_index(
        op.f("ix_appointments_patient_id"), table_name="appointments"
    )
    op.drop_index(op.f("ix_appointments_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_doctor_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_date"), table_name="appointments")
    op.drop_table("appointments")
    op.drop_index(op.f("ix_patients_user_id"), table_name="patients")
    op.drop_index(op.f("ix_patients_id"), table_name="patients")
    op.drop_index(op.f("ix_patients_gender_id"), table_name="patients")
    op.drop_index(op.f("ix_patients_birth_date"), table_name="patients")
    op.drop_index(op.f("ix_patients_address"), table_name="patients")
    op.drop_table("patients")
    op.drop_index(op.f("ix_doctors_user_id"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_profile_id"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_name"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_id"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_gender_id"), table_name="doctors")
    op.drop_table("doctors")
    op.drop_index(op.f("ix_users_role_id"), table_name="users")
    op.drop_index(op.f("ix_users_login"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_services_profile_id"), table_name="services")
    op.drop_index(op.f("ix_services_name"), table_name="services")
    op.drop_index(op.f("ix_services_id"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_profiles_name"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_id"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_places_name"), table_name="places")
    op.drop_index(op.f("ix_places_id"), table_name="places")
    op.drop_index(op.f("ix_places_address"), table_name="places")
    op.drop_table("places")
    op.drop_index(op.f("ix_genders_name"), table_name="genders")
    op.drop_index(op.f("ix_genders_id"), table_name="genders")
    op.drop_table("genders")
    # ### end Alembic commands ###
