"""empty message

Revision ID: d1dec151c7ef
Revises: 140c6a9f4071
Create Date: 2024-08-12 18:42:06.932220

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d1dec151c7ef"
down_revision: Union[str, None] = "140c6a9f4071"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "multimedia",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("url", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_multimedia_id"), "multimedia", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_multimedia_url"), "multimedia", ["url"], unique=True
    )
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("surname", sa.String(length=30), nullable=False),
        sa.Column("patronymic", sa.String(length=30), nullable=True),
        sa.Column("multimedia_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["multimedia_id"],
            ["multimedia.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admins_id"), "admins", ["id"], unique=False)
    op.create_index(
        op.f("ix_admins_multimedia_id"),
        "admins",
        ["multimedia_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admins_user_id"), "admins", ["user_id"], unique=False
    )
    op.add_column(
        "doctors", sa.Column("multimedia_id", sa.Integer(), nullable=True)
    )
    op.drop_index("ix_doctors_name", table_name="doctors")
    op.create_index(
        op.f("ix_doctors_multimedia_id"),
        "doctors",
        ["multimedia_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "doctors", "multimedia", ["multimedia_id"], ["id"]
    )
    op.add_column(
        "patients", sa.Column("multimedia_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_patients_multimedia_id"),
        "patients",
        ["multimedia_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "patients", "multimedia", ["multimedia_id"], ["id"]
    )
    op.add_column(
        "places", sa.Column("multimedia_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_places_multimedia_id"),
        "places",
        ["multimedia_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "places", "multimedia", ["multimedia_id"], ["id"]
    )
    op.add_column(
        "reviews", sa.Column("multimedia_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_reviews_multimedia_id"),
        "reviews",
        ["multimedia_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "reviews", "multimedia", ["multimedia_id"], ["id"]
    )
    op.add_column(
        "users",
        sa.Column("phone_number", sa.String(length=12), nullable=False),
    )
    op.drop_index("ix_users_login", table_name="users")
    op.create_index(
        op.f("ix_users_phone_number"), "users", ["phone_number"], unique=True
    )
    op.drop_column("users", "login")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "login", sa.VARCHAR(length=12), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.create_index("ix_users_login", "users", ["login"], unique=True)
    op.drop_column("users", "phone_number")
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.drop_index(op.f("ix_reviews_multimedia_id"), table_name="reviews")
    op.drop_column("reviews", "multimedia_id")
    op.drop_constraint(None, "places", type_="foreignkey")
    op.drop_index(op.f("ix_places_multimedia_id"), table_name="places")
    op.drop_column("places", "multimedia_id")
    op.drop_constraint(None, "patients", type_="foreignkey")
    op.drop_index(op.f("ix_patients_multimedia_id"), table_name="patients")
    op.drop_column("patients", "multimedia_id")
    op.drop_constraint(None, "doctors", type_="foreignkey")
    op.drop_index(op.f("ix_doctors_multimedia_id"), table_name="doctors")
    op.create_index("ix_doctors_name", "doctors", ["name"], unique=False)
    op.drop_column("doctors", "multimedia_id")
    op.drop_index(op.f("ix_admins_user_id"), table_name="admins")
    op.drop_index(op.f("ix_admins_multimedia_id"), table_name="admins")
    op.drop_index(op.f("ix_admins_id"), table_name="admins")
    op.drop_table("admins")
    op.drop_index(op.f("ix_multimedia_url"), table_name="multimedia")
    op.drop_index(op.f("ix_multimedia_id"), table_name="multimedia")
    op.drop_table("multimedia")
    # ### end Alembic commands ###
